### ISSUE TITLE
Incorrect HEADER_SEARCH_PATHS after import...

### ISSUE THREAD

**Issue by rorywalsh** [McMartin/FRUT#587] opened 2020-01-23 14:35 UTC
Hi @McMartin . I'm excited to get going with this but have a hit a minor issue on the first attempt. The header paths from my Projucer files import correctly. They look like this:

```
  HEADER_SEARCH_PATHS
    "Builds/LinuxMakefile/\"/usr/local/include/csound\""
    "Builds/LinuxMakefile/\"/usr/include/csound\""
    "Builds/LinuxMakefile/\"~/SDKs/VST_SDK/VST3_SDK\""
```
I can manually edit them and move on from there, but thought it might be worth noting in case I am doing something wrong?

**Comment by McMartin** [comment] 2020-01-23 14:41
Hi @rorywalsh,

Thanks a lot for using FRUT!

I think what you are experiencing is a bug in Jucer2Reprojucer. However, it's a bit hard for me to figure out what is wrong... Could you please copy-paste the part of your `.jucer` file that contains the `headerPath` attribute and these 3 paths? I'll try to reproduce the issue then. Thanks!

**Comment by rorywalsh** [comment] 2020-01-23 16:32
Here you go:
```
        <CONFIGURATION name="Debug" isDebug="1" optimisation="1" targetName="CabbagePlugin"
                       headerPath="/usr/local/include/csound&#10;/usr/include/csound&#10;~/SDKs/VST_SDK/VST3_SDK"
                       libraryPath="/usr/local/lib" defines="Cabbage_Plugin_Synth=1"/>
        <CONFIGURATION name="Release" isDebug="0" optimisation="3" targetName="CabbagePlugin"
                       headerPath="/usr/local/include/csound&#10;/usr/include/csound&#10;~/SDKs/VST_SDK/VST3_SDK"
                       libraryPath="/usr/local/lib" defines="Cabbage_Plugin_Synth=1"/>
```
I'm sure why, but Producer adds the '&#10' to the paths each time I save my .jucer file. Thanks.

**Comment by McMartin** [comment] 2020-01-23 16:40
`&#10;` encodes a New Line (LF) character.

**Comment by McMartin** [comment] 2020-01-23 16:56
Unfortunately I can't reproduce... When I put your code into a `.jucer` file and convert it using `Jucer2Reprojucer` I get:
```cmake
ucer_export_target_configuration(
  "Linux Makefile"
  NAME "Debug"
  DEBUG_MODE ON
  BINARY_NAME "CabbagePlugin"
  HEADER_SEARCH_PATHS
    "/usr/local/include/csound"
    "/usr/include/csound"
    "~/SDKs/VST_SDK/VST3_SDK"
  EXTRA_LIBRARY_SEARCH_PATHS
    "/usr/local/lib"
  PREPROCESSOR_DEFINITIONS
    "Cabbage_Plugin_Synth=1"
  OPTIMISATION "-O0 (no optimisation)"
)

jucer_export_target_configuration(
  "Linux Makefile"
  NAME "Release"
  DEBUG_MODE OFF
  BINARY_NAME "CabbagePlugin"
  HEADER_SEARCH_PATHS
    "/usr/local/include/csound"
    "/usr/include/csound"
    "~/SDKs/VST_SDK/VST3_SDK"
  EXTRA_LIBRARY_SEARCH_PATHS
    "/usr/local/lib"
  PREPROCESSOR_DEFINITIONS
    "Cabbage_Plugin_Synth=1"
  OPTIMISATION "-O3 (fastest with safe optimisations)"
)
```

Could you please give me as much detail as possible wrt. to how you built and ran `Jucer2Reprojucer`, including platform, compiler version, CMake version, CMake generator, JUCE version, FRUT commit, etc.? Maybe there is something platform specific or JUCE version specific that could explain this behavior.

**Comment by rorywalsh** [comment] 2020-01-23 17:06
* JUCE 5.4.5
* Cmake 3.16.3
* I downloaded a zip of the FRUT master today
* I'm running -G "Unix Makefiles"
* Platform: Linux 18.04
* gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

When you put the paths into your sample Projucer file are you enclosing them in quotes? I tried both with and without and still get the same issues. 

To run, I created the folder structure you advise in your instructions, then I run:

../frut/prefix/FRUT/bin/Jucer2Reprojucer CabbagePluginSynth.jucer ../frut/prefix/FRUT/cmake/Reprojucer.cmake

>Note I did change the folder containing FRUT to frut.. I'm a little caps-lock lazy...

Then I go through the typical cmake motions. Create a build folder, and run the generator from that. I can't think of anything else that might be causing issues Not that I have a few jucer files in my project root folder, but I guess that shouldn't make any difference. FWIW, [here](https://github.com/rorywalsh/cabbage/tree/develop) is my project repo. It's a little obfuscated due to there being 4 projects which live and build out of the same repo :roll_eyes:  Which will warrant a fresh barrage of questions in due time :rofl:

**Comment by McMartin** [comment] 2020-01-23 17:49
```
headerPath="/usr/local/include/csound&#10;/usr/include/csound&#10;~/SDKs/VST_SDK/VST3_SDK"
```
and
```
headerPath="&quot;/usr/local/include/csound&quot;&#10;&quot;/usr/include/csound&quot;&#10;&quot;~/SDKs/VST_SDK/VST3_SDK&quot;"
```
are not the same thing, and indeed `Jucer2Reprojucer` doesn't handle the second case properly.

With the second case, I can reproduce and I know what to fix. Stay tuned!

**Comment by rorywalsh** [comment] 2020-01-23 18:02
Super. Thanks for the speedy support.

**Comment by McMartin** [comment] 2020-01-23 19:00
@rorywalsh I opened https://github.com/McMartin/FRUT/pull/588 to fix the issue. Feel free to give it a try.

**Comment by rorywalsh** [comment] 2020-01-23 22:53
Super, I'll try it out when I get a chance.

**Comment by rorywalsh** [comment] 2020-01-24 04:14
That did the trick. Thanks @McMartin. I'll close this issue out now. Thanks.

**Comment by McMartin** [comment] 2020-01-24 08:45
Let's keep this issue open until https://github.com/McMartin/FRUT/pull/588 is merged. Merging https://github.com/McMartin/FRUT/pull/588 will automatically close it.

**Closed** 2020-01-25 21:32 UTC
Labels: bug
