### ISSUE TITLE
FRUT and CLion

### ISSUE THREAD

**Issue by rorywalsh** [McMartin/FRUT#589] opened 2020-01-24 05:02 UTC
It seems that CLion always calls the CodeBlocks generator when opening a CMake based project :roll_eyes: This causes a cmake error in Reprojucer.cmake, as can be seen in the CLion cmake output below.

```
/usr/local/bin/cmake -DCMAKE_BUILD_TYPE=Debug -G "CodeBlocks - Unix Makefiles" /home/rory/sourcecode/cabbage
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /home/rory/sourcecode/frut/prefix/FRUT/cmake/Reprojucer.cmake:2026 (message):
  You must call jucer_export_target("Code::Blocks (Linux)") before calling
  jucer_project_end().
Call Stack (most recent call first):
  CMakeLists.txt:607 (jucer_project_end)


-- Configuring incomplete, errors occurred!
See also "/home/rory/sourcecode/cabbage/clion-debug-build/CMakeFiles/CMakeOutput.log".

[Failed to reload]
```
Manually editing the CMakelists file fixes the error, but is there a way to avoid having to change the generated CMakeLists file? In the case of CI builds it's kind of awkward..

[edit] It's too early for me, of course this won't affect my CI builds as I will be generating straight up Unix Makefiles! So this is not that big of an issue. Manually editing the CMakeLists file is not a big deal.

**Comment by McMartin** [comment] 2020-01-24 09:26
> Manually editing the CMakelists file fixes the error 

Then you are lucky not to have any settings that are specific to the `Linux Makefile` exporter and that the `Code::Blocks (Linux)` exporter doesn't support, such as `PKGCONFIG_LIBRARIES`.

> but is there a way to avoid having to change the generated CMakeLists file?

I can think of 2 options:
- Make CLion use the `Unix Makefiles` generator instead of the `CodeBlocks - Unix Makefiles` generator. However, I guess CLion is using `CodeBlocks - Unix Makefiles` by default for a good reason and it might make the experience of using that IDE suboptimal.
- Make it possible to select the current exporter instead of letting `Reprojucer.cmake` figure it out on its own. One would still need to change how CLion calls CMake, but it would be maybe less disruptive.

I'm setting up an Ubuntu 18.04 VM to test this and see which option should be preferred.

**Comment by rorywalsh** [comment] 2020-01-24 10:23
From what I've [seen](https://youtrack.jetbrains.com/issue/CPP-8813?_ga=2.4780915.1953272572.1579797950-1530438595.1545839813) CLion doesn't let you modify how it works with CMake. So perhaps you needn't waste your time on this?

**Comment by McMartin** [comment] 2020-01-24 10:27
The CLion issue you linked to is quite old. CLion does support other CMake generators since version 2019.3 (https://blog.jetbrains.com/clion/2019/10/clion-2019-3-eap-ninja-cmake-generators/). I guess you could give a try to Ninja.

**Comment by McMartin** [comment] 2020-01-24 14:15
I reproduced this issue in a VM that runs Ubuntu 18.04.3 and CLion 2019.3.3. I got CMake to work by putting `-G"Unix Makefiles"` or `-G"Ninja"` in the "CMake options" field of the CLion settings.

I think this solution (which is the first option mentioned here: https://github.com/McMartin/FRUT/issues/589#issuecomment-578054662) is perfectly acceptable as long as one can use a version of CLion that is recent enough (2019.3+). However, I don't want to force people to upgrade their version of CLion if they can't.

@rorywalsh please let me know whether you can use CLion 2019.3+, in which case we can close this issue. Otherwise, I'll work on supporting the "manually" selection of the exporter in `Reprojucer.cmake`. Thanks!

**Comment by rorywalsh** [comment] 2020-01-24 14:18
Thanks. I can upgrade, that's not an issue. Great, that's another tick in
the pros column for FRUT!

**Closed** 2020-01-24 14:21 UTC
Labels: enhancement
