### ISSUE TITLE
Default architecture is i386, while through the Projucer it isn't

### ISSUE THREAD

**Issue by stijnfrishert** [McMartin/FRUT#473] opened 2019-03-19 17:30 UTC
When using FRUT to generate an XCode project through my generated CMakeLists.txt, Xcode throws up the following error:

    error: The i386 architecture is deprecated. You should update your ARCHS build setting to remove the i386 architecture.

When I generate an XCode project from my Projucer directly, the architecture is fine.

The OSX Architecture field in my Projucer is set to Default. When I change it to 64-bit Intel, the generated XCode project works, so it looks like the default isn't being detected correctly by FRUT.

**Comment by McMartin** [comment] 2019-03-19 22:26
@stijnfrishert thanks for trying out FRUT and creating that issue!

Projucer sets a lot of Xcode settings, and I admit that I didn't make `Reprojucer.cmake` set all of them in the exact same way. However, I think I found the Xcode setting that `Reprojucer.cmake` doesn't set that is responsible for that warning. I pushed a branch called [`wip/set-ONLY_ACTIVE_ARCH-Xcode-setting`](https://github.com/McMartin/FRUT/tree/wip/set-ONLY_ACTIVE_ARCH-Xcode-setting) with a potential fix. Please give it a try, and let me know if that solves your issue, thanks!

**Comment by stijnfrishert** [comment] 2019-03-20 08:04
Yes, that works! Thanks for the quick reaction. :)

Project still doesn't fully build to missing frameworks, but that's another issue. Architecture works as expected now.

**Comment by McMartin** [comment] 2019-03-20 22:09
As explained in https://github.com/McMartin/FRUT/pull/474#issuecomment-475041586, the changes I did on the branch `wip/set-ONLY_ACTIVE_ARCH-Xcode-setting` were not correct. So let's take a step back and try to understand what is really going on:
- which version of macOS, Xcode and CMake are you using?
- what kind of project are you building? 
  - if you can, please attach the `CMakeLists.txt` generated by `Jucer2Reprojucer` in a comment (feel free to remove/change any line that contains "sensitive" information)
  - if you can, please also attach the `.jucer` file that you are asking `Jucer2Reprojucer` to convert (again, feel free to obfuscate its contents) 
- where exactly do you see the error that you reported in your first post?
  - if in the Xcode UI, in which panel? When doing which action exactly?
  - if in the terminal, when running which command?

**Comment by stijnfrishert** [comment] 2019-03-21 08:35
Ok, I'll rerun this when I find the time! Just upgraded that system to Mojave yesterday actually, so the situation might've changed too.

**Comment by stijnfrishert** [comment] 2019-03-22 15:31
Ok, ran through the process on my development machine. Followed the exact same steps as outlined in your readme, except for a different location of -DJUCE_ROOT. Used the most recent version of FRUT I could find on the master branch.

 - macOS 10.13.6 (High Sierra)
 - XCode 10.1 (10B61)
 - CMake 3.13.4

Not sure what changed, but building now works (up to using custom frameworks #442). The Xcode project has the setting Valid Architectures set to `i386 x64_64`.

Could be the issue only arises on my Macbook Air, so I could check back in and see what happens there if you'd like?

**Comment by McMartin** [comment] 2019-03-22 16:46
> Not sure what changed, but building now works

> Could be the issue only arises on my Macbook Air, so I could check back in and see what happens there if you'd like?

That's totally up to you. You can keep this issue open if you intend to check on your Macbook Air, or you can close this issue if you're fine with the current state of affairs.

> up to using custom frameworks #442

That's definitely on my short-term TODO list.

**Comment by stijnfrishert** [comment] 2019-03-24 21:27
Alright, tried again on my MBA, and the problem rears its head again. :)

System specs:
 - macOS 10.14.3 (Mojave)
 - XCode 10.1 (10B61)
 - CMake 3.13.4

In other words, the only thing that has changed is my macOS version.
Running `cmake -G Xcode ..` and then `cmake --build .` gives the following error:

    Check dependencies
    error: The i386 architecture is deprecated. You should update your ARCHS build setting to remove the i386 architecture.

    ** BUILD FAILED **

**Comment by stijnfrishert** [comment] 2019-03-24 21:28
> 
> > up to using custom frameworks #442
> 
> That's definitely on my short-term TODO list.

Great to hear! I'd be fine with using the unix makefile gen, but the Projucer doesn't let you set specific macOS build data outside of Xcode projects,  right?

**Comment by McMartin** [comment] 2019-03-25 10:17
> In other words, the only thing that has changed is my macOS version.

I guess `xcodebuild` behaves differently on macOS 10.14 than on macOS 10.13, since the 10.14 SDK doesn't support 32-bit anymore. I'll try to get my hands on a Mac that runs macOS 10.14 to reproduce, but it might take me quite a while...

> I'd be fine with using the unix makefile gen, but the Projucer doesn't let you set specific macOS build data outside of the Xcode project exporter, right?

Using the Unix Makefiles generator would indeed be a good workaround to the `xcodebuild` issue, but I don't understand your question. What kind of "macOS build data" are you referring to? Some features of Projucer are indeed only available when using the Xcode generator of CMake (`USE_HEADERMAP`, `CUSTOM_XCODE_FLAGS`, and `CODE_SIGNING_IDENTITY`), but unless you rely on them, you should be able to use the Unix Makefiles generator.

**Closed** 2019-11-01 16:16 UTC
Labels: bug
