### ISSUE TITLE
How to build for VS 2022

### ISSUE THREAD

**Issue by robbiehinch** [McMartin/FRUT#774] opened 2024-09-19 10:03 UTC
Hi, I'm following the guide here:

https://github.com/McMartin/FRUT?tab=readme-ov-file#getting-started

At the 
$ cmake .. -G<generator>
I'm not sure what to enter for the generator, cmake doesn't seem to like either of _**Visual Studio 17 2022**_ or _**Visual Studio 2022**_
I feel like my setup is ok, because I was able to build FRUT using cmake.
Here's the output with the two different error cases:
```

PS C:\projects\vst\Plugins\MyGreatProject\build> & "C:\Program Files\CMake\bin\cmake.exe" .. -G "Visual Studio 17 2022"
CMake Deprecation Warning at CMakeLists.txt:3 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.22631.
-- The C compiler identification is MSVC 19.41.34120.0
-- The CXX compiler identification is MSVC 19.41.34120.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at C:/projects/vst/FRUT/prefix/FRUT/cmake/Reprojucer.cmake:2294 (message):
  Reprojucer.cmake doesn't support any export target for your current
  platform.  It supports the following export targets:

    - Xcode (macOS)
    - Xcode (iOS)
    - Visual Studio 2022
    - Visual Studio 2019
    - Visual Studio 2017
    - Visual Studio 2015
    - Visual Studio 2013
    - Linux Makefile
    - Code::Blocks (Windows)
    - Code::Blocks (Linux).

  If you think Reprojucer.cmake should support another export target, please
  create an issue on GitHub: https://github.com/McMartin/FRUT/issues/new

Call Stack (most recent call first):
  CMakeLists.txt:242 (jucer_project_end)


-- Configuring incomplete, errors occurred!
PS C:\projects\vst\Plugins\MyGreatProject\build> & "C:\Program Files\CMake\bin\cmake.exe" .. -G "Visual Studio 2022"
CMake Error: Could not create named generator Visual Studio 2022

Generators
* Visual Studio 17 2022        = Generates Visual Studio 2022 project files.
                                 Use -A option to specify architecture.
  Visual Studio 16 2019        = Generates Visual Studio 2019 project files.
                                 Use -A option to specify architecture.
  Visual Studio 15 2017 [arch] = Generates Visual Studio 2017 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 14 2015 [arch] = Generates Visual Studio 2015 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 12 2013 [arch] = Deprecated.  Generates Visual Studio 2013
                                 project files.  Optional [arch] can be
                                 "Win64" or "ARM".
  Visual Studio 9 2008 [arch]  = Deprecated.  Generates Visual Studio 2008
                                 project files.  Optional [arch] can be
                                 "Win64" or "IA64".
  Borland Makefiles            = Generates Borland makefiles.
  NMake Makefiles              = Generates NMake makefiles.
  NMake Makefiles JOM          = Generates JOM makefiles.
  MSYS Makefiles               = Generates MSYS makefiles.
  MinGW Makefiles              = Generates a make file for use with
                                 mingw32-make.
  Green Hills MULTI            = Generates Green Hills MULTI files
                                 (experimental, work-in-progress).
  Unix Makefiles               = Generates standard UNIX makefiles.
  Ninja                        = Generates build.ninja files.
  Ninja Multi-Config           = Generates build-<Config>.ninja files.
  Watcom WMake                 = Generates Watcom WMake makefiles.
  CodeBlocks - MinGW Makefiles = Generates CodeBlocks project files
                                 (deprecated).
  CodeBlocks - NMake Makefiles = Generates CodeBlocks project files
                                 (deprecated).
  CodeBlocks - NMake Makefiles JOM
                               = Generates CodeBlocks project files
                                 (deprecated).
  CodeBlocks - Ninja           = Generates CodeBlocks project files
                                 (deprecated).
  CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files
                                 (deprecated).
  CodeLite - MinGW Makefiles   = Generates CodeLite project files
                                 (deprecated).
  CodeLite - NMake Makefiles   = Generates CodeLite project files
                                 (deprecated).
  CodeLite - Ninja             = Generates CodeLite project files
                                 (deprecated).
  CodeLite - Unix Makefiles    = Generates CodeLite project files
                                 (deprecated).
  Eclipse CDT4 - NMake Makefiles
                               = Generates Eclipse CDT 4.0 project files
                                 (deprecated).
  Eclipse CDT4 - MinGW Makefiles
                               = Generates Eclipse CDT 4.0 project files
                                 (deprecated).
  Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files
                                 (deprecated).
  Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files
                                 (deprecated).
  Kate - MinGW Makefiles       = Generates Kate project files (deprecated).
  Kate - NMake Makefiles       = Generates Kate project files (deprecated).
  Kate - Ninja                 = Generates Kate project files (deprecated).
  Kate - Ninja Multi-Config    = Generates Kate project files (deprecated).
  Kate - Unix Makefiles        = Generates Kate project files (deprecated).
  Sublime Text 2 - MinGW Makefiles
                               = Generates Sublime Text 2 project files
                                 (deprecated).
  Sublime Text 2 - NMake Makefiles
                               = Generates Sublime Text 2 project files
                                 (deprecated).
  Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files
                                 (deprecated).
  Sublime Text 2 - Unix Makefiles
                               = Generates Sublime Text 2 project files
                                 (deprecated).

PS C:\projects\vst\Plugins\MyGreatProject\build> & "C:\Program Files\CMake\bin\cmake.exe" -version
cmake version 3.29.3

```

**Comment by gdeankrotos** [comment] 2024-09-19 12:04
I've been encountering this issue as well. It appears to be caused by using the latest versions of Visual Studio 2022 17.10+ as these include a version of MSVC newer than what is currently supported by reproducer. 
Your log indicates you are using MSVC 19.41.34120.0

Reproducer.cmake currently throws this error as the latest version of MSVC it supports is seemingly 1939:
`set(Reprojucer_supported_exporters_conditions
"MSVC_VERSION\;GREATER\;1929\;AND\;MSVC_VERSION\;LESS\;1940"`

Try rolling back to Visual Studio 2022 17.9 as this comes with MSVC 1939:
https://learn.microsoft.com/en-us/cpp/overview/compiler-versions?view=msvc-170#version-macros

Will look into raising a PR to fix this

**Comment by McMartin** [comment] 2024-09-20 13:33
Hi,

This issue was fixed in https://github.com/McMartin/FRUT/pull/775. Let me know if something still doesn't work when using VS2022.

**Closed by McMartin** 2024-09-20 13:33 UTC
